<html>
    <head>
        <title>管理员登录</title>
    </head>

    <body>
        <form action="/admin/login/doLogin" method="post">
            <table>
                <tr>
                    <td></td>
                    <td>管理员登录</td>
                </tr>
                <tr>
                    <td><label>用户名</label>：</td>
                    <td><input type="text" name="admin_id" placeholder="请输入管理员ID"></td>
                </tr>
                <tr>
                    <td><label>密码</label>：</td>
                    <td><input type="password" name="adm_password" placeholder="请输入密码"></td>
                </tr>
                <tr>
                    <td><label>验证码</label>：</td>
                    <td>
                        <input type="text" name="captcha" placeholder="请输入验证码">
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <div>
                            <img class="captcha" src="{:captcha_src()}"
                                 alt="点击刷新"
                                 onclick="this.src='{:captcha_src()}'"/>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td><input type="submit" name="登录"></td>
                </tr>
            </table>
        </form>
    </body>
</html>